machine:
  java:
    version: oraclejdk8
  node:
    version: 5.2.0

dependencies:
  cache_directories:
    - "~/.meteor"

  override:
    # Cache Meteor
    - if [ -d ~/.meteor ]; then sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor; fi
    - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

    # Cache npm deps
    - npm install

    - ./node_modules/.bin/chimp --path=features:
      pwd: .scripts
